authentication_app/urls.py
from django.urls import path
from typing import Type, List, Any

from authentication_app import views
from authentication_app.apps import AuthenticationAppConfig

app_name = AuthenticationAppConfig.name

urlpatterns: List[Type[Any]] = [
    # Home View
    path("", views.HomeView.as_view(), name="home"),

    # Custom Login View
    path("login/", views.CustomLoginView.as_view(), name="login"),

    # Custom Logout View
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),

    # Register View
    path("register/", views.RegisterView.as_view(), name="register"),

    # Profile Edit View
    path("profile_edit/<int:pk>/", views.ProfileEditView.as_view(), name="profile_edit"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url="home/")),
    path('home/', include('authentication_app.urls', namespace='authentication_app')),
    path('files/', include('file_upload_app.urls', namespace='file_upload_app')),
    path('reports/', include('reports_app.urls', namespace='reports_app')),
    path('api/v1/auth/', include('authentication_app.api.urls')),
    path('api/v1/get/', include('file_upload_app.api.urls')),
    path('api/v1/check/', include('code_verification_app.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file_upload_app/urls.py
from django.urls import path
from . import views


app_name = 'file_upload_app'

urlpatterns = [
    path('upload/', views.FileUploadView.as_view(), name='upload_file'),
    path('my-files/', views.MyFilesView.as_view(), name='my_files'),
    path('delete-file/<int:pk>/', views.DeleteFileView.as_view(), name='delete_file'),
    path('overwrite-file/<int:pk>/', views.OverwriteFileView.as_view(), name='overwrite_file'),

]

reports_app/urls.py
from django.urls import path
from . import views


app_name = 'reports_app'

urlpatterns = [
    path('results/', views.ReportListView.as_view(), name='results'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/my_styles.css'%}">

    <title>
        {% block title %}
        Welcome!
        {% endblock title %}
    </title>
</head>

<body class="page-container">

    {% block messages %}
    {% include 'includes/messages.html' %}
    {% endblock messages %}
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'authentication_app:home' %}">
                <img class="logo" src="{% static 'img/logo.png' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item {% if request.resolver_match.view_name == 'authentication_app:home' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'authentication_app:home' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authentication_app:profile_edit' pk=request.user.pk %}">Редактировать профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'file_upload_app:upload_file' %}">Загрузить файл</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'file_upload_app:my_files' %}">Мои файлы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reports_app:results' %}">Мои отчёты</a>
                    </li>
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Административный раздел</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authentication_app:logout' %}">Выход</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="content-container mb-5">
        {% block content %}
        Что-то пошло не так...
        {% endblock content %}
    </div>

    <div class="footer">
        <hr>
        <div>
            <div class="row justify-content-center">
                <div class="col-sm-6 col-md-3 text-center">
                    <p>
                        <strong>Skypro</strong>
                    </p>
                    <p>
                        <ul class="list-unstyled">
                            <li><a href="{% url 'authentication_app:home' %}">Домашняя</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'authentication_app:logout' %}">Выйти</a></li>
                            {% else %}
                            <li><a href="{% url 'authentication_app:login' %}">Войти</a></li>
                            {% endif %}
                        </ul>
                    </p>
                </div>
                <div class="col-sm-6 col-md-3 text-center">
                    <p>
                        <strong>Полезное</strong>
                    </p>
                    <p>
                        <ul class="list-unstyled">
                            <li><a href="#">Положения &amp; Условия</a></li>
                            <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                        </ul>
                    </p>
                </div>
                <div class="col-sm-6 col-md-3 text-center">
                    <p>
                        <strong>Мы в социальных сетях</strong>
                    </p>
                    <p>
                        <div class="row justify-content-around">
                            <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                            <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                            <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>
    {% block js %}
    <script>
        $(document).ready(function () {

        {% if messages %}
        // Toasts
        $(".toast").toast({ delay: 5000 });
        $(".toast").toast("show");
        {% endif %}

        });
    </script>
    {% endblock js %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron text-center">
        <div class="container">
            <h1 class="display-4">Добро пожаловать в сервис проверки Python кода!</h1>
            <p class="lead">Мы рады приветствовать вас в нашем удивительном мире кода и разработки.</p>
            <hr class="my-4">
            {% if not user.is_authenticated %}
            <p>Если вы здесь впервые, вы можете <a href="{% url 'authentication_app:register' %}" class="btn btn-success">зарегистрироваться</a> и начать пользоваться всеми нашими возможностями.</p>
            <p>Если у вас уже есть аккаунт, просто <a href="{% url 'authentication_app:login' %}" class="btn btn-primary">войдите</a>.</p>
            {% else %}
            <p>Спасибо, что выбрали нас для проверки вашего Python кода! Теперь вы можете загружать свои проекты, проверять их на соответствие стандартам и получать отчеты о качестве вашего кода.</p>
            <p>Мы упростим вашу разработку и поможем вам создавать лучший код.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}